dist: xenial
language: php

matrix:
  include:
    - php: 7.1
      env: TESTBENCH_VERSION="3.5.*"
    - php: 7.1
      env: TESTBENCH_VERSION="3.6.*"
    - php: 7.1
      env: TESTBENCH_VERSION="3.7.*"
    - php: 7.1
      env: TESTBENCH_VERSION="3.8.*"

    - php: 7.2
      env: TESTBENCH_VERSION="3.5.*"
    - php: 7.2
      env: TESTBENCH_VERSION="3.6.*"
    - php: 7.2
      env: TESTBENCH_VERSION="3.7.*"
    - php: 7.2
      env: TESTBENCH_VERSION="3.8.*"
    - php: 7.2
      env:
        - TESTBENCH_VERSION="4.0.*"
        - COVERAGE_UPLOAD=1
    - php: 7.2
      env: TESTBENCH_VERSION="4.2"

    - php: 7.3
      env: TESTBENCH_VERSION="3.5.*"
    - php: 7.3
      env: TESTBENCH_VERSION="3.6.*"
    - php: 7.3
      env: TESTBENCH_VERSION="3.7.*"
    - php: 7.3
      env: TESTBENCH_VERSION="3.8.*"
    - php: 7.3
      env: TESTBENCH_VERSION="4.0"
    - php: 7.3
      env: TESTBENCH_VERSION="4.2"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer remove php --no-update
  - travis_retry composer require php=$(phpenv version-name).* --no-update
  - travis_retry composer remove phpunit/phpunit --no-update --dev
  - travis_retry composer remove orchestra/testbench --no-update --dev
  - travis_retry composer require orchestra/testbench=${TESTBENCH_VERSION} --no-update --dev
  - if [[ "$COMPOSER_STABILITY" != "" ]]; then composer config minimum-stability ${COMPOSER_STABILITY}; fi
  - cat composer.json
  - travis_retry composer update --no-interaction --prefer-dist --prefer-stable

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$COVERAGE_UPLOAD" == "1" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
